### ISSUE TITLE
hex2bin(): Hexadecimal input string must have an even length

### ISSUE THREAD

**Issue by anoduck** [vichan-devel/vichan#296]
Just completed dependency installation, edited php.config to add categories and board links. Restarted my server software along with php_fpm. Tested out replying to a post, received the following error:

``hex2bin(): Hexadecimal input string must have an even length``

This does not look like an issue with a missing dependency. I might have a library that is out of date, so I am updating what I can at the moment. Suspected the error has more to do with my current version of php, which is 7.0.23, but possibly not. 

There are solutions to this issue, but they involve breaking out a text editor and tinkering with the code. I would prefer to trust the developer and trust his code for the moment, the probability being there is another solution to this error.

**Comment by anoduck** [comment]
This issue has more to do with a bug within php, rather than a bug in vichan. So, going ahead and closing this one out. I

**Comment by ctrlcctrlv** [comment]
@anoduck No can do. If this is a regression in PHP 7.0, I need to fix it. I need more details. What file, what line number, what did you do to fix it. This code is maintained by the community, you can contribute.

**Comment by anoduck** [comment]
Sure thing, glad to hear it.

It isn't fixed, still broken. I have no solution as of yet. Even after downgrading to php 5.6 still getting errors, and it is the same story with the upstream repos as well. 

I ran into difficulties in both OpenBSD with php-7.0.28 and Alpine Linux with php-7.2.6. Every time I went to post to the board I received the following error:

    hex2bin(): Hexadecimal input string must have an even length

 After receiving the error the post would be published regardless. The error would occur also when the board was being rebuilt. Once I removed all posts from the thread it would only then clear up and rebuild smoothly. 

After the initial error is received, it is easily reproduced by attempting to rebuild the board as mentioned above in this redundant comment. 

I will be attaching the output of such error here: 

```
Array
(
    [file] => /path/to/vichan/inc/api.php:97
    [errno] => 2
    [error] => hex2bin(): Hexadecimal input string must have an even length
    [backtrace] => Array
        (
            [0] => Array
                (
                    [file] => /path/to/vichan/inc/functions.php
                    [line] => 386
                    [function] => error
                    [args] => Array
                        (
                            [0] => hex2bin(): Hexadecimal input string must have an even length
                            [1] => 1
                            [2] => Array
                                (
                                    [file] => /path/to/vichan/inc/api.php:97
                                    [errno] => 2
                                    [error] => hex2bin(): Hexadecimal input string must have an even length
                                    [backtrace] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [file] => /path/to/vichan/inc/api.php
                                                    [line] => 97
                                                    [function] => hex2bin
                                                    [args] => Array
                                                        (
                                                            [0] => sh:
                                                        )

                                                )

                                            [1] => Array
                                                (
                                                    [file] => /path/to/vichan/inc/api.php
                                                    [line] => 133
                                                    [function] => translateFile
                                                    [class] => Api
                                                    [object] => Api Object
                                                        (
```

So, because learning is the process of discovery. I sat through and looked at the error again, and this time I saw the error occured inside of api.php, reviewed the configuration file, and disabled the 4chan api compatibility. 

After which that particular error did not occur, but instead I received the error that the post already existed. 

```
That file already exists!

Go back
Error information

Array
(
    [backtrace] => Array
        (
            [0] => Array
                (
                    [file] => /path/to/vichan/post.php
                    [line] => 1025
                    [function] => error
                    [args] => Array
                        (
                            [0] => That file <a href="/mod.php?/b/res/6.html">already exists</a>!
                        )

                )

        )

)
```

I am going to disable `image_reject_repost` and enable rejecting reposting per thread, and see if that does anything... and it doesn't... bummer...

So that is where we land for now. What else needs to be posted to aid diagnoses?

**Comment by anoduck** [comment]
To quote the great Jeremy Clarkson, "I MENDED SOMETHING!" ...locally...

So after disabling 4chan api compatibility, I began to receive the error that the image already existed everytime I went to upload a photo after the first post. This was because I had enabled `reject_repost` globally, and `post.php` was attempting to call md5 from the wrong directory in openbsd, which is located in `/bin` not `/sbin`.  Once I fired up the text editor and removed the "s" from the string, it was working fine. 

I do not know php, it can't be too hard though, and I am not sure how you want to incorporate the fix into the pre-existing code. The big question being, where does freebsd, mirbsd, and netbsd store md5?  Either another option needs to be present, or the current code changed, to point out the obvious. I am not comfortable with making that decision, so it is up to someone else in the community with more experience, and a name tag. 

-----

### rebuild script via command line

The next hurdle to climb is neither of the rebuild.php scripts located in `/tools` are functioning from the command line in OpenBSD. Without the ability to execute `rebuild.php` from the command line, the crontab job to update and rebuild the board every so often will not be able to run. Meaning a manually executed rebuild from the web ui  is required to update the site.  

The error for execution of "rebuild.php" is:

<code>
  Error: Undefined index: dir
  #0 error() called at [/path/to/vichan/inc/functions.php:386]
</code>

The error for executing "rebuild2.php" is:

<code>
  Uncaught Error: Call to undefined function pcntl_fork() in /path/to/rebuild2.php:109
</code>

I have php7-pcntl installed, fyi. 

-----


### Alpine Linux Errors


In alpine I am recieving a different set of errors. Now, I am recieving the following message, with a crap load of debugging information. 

```
Error
An error has occured.
count(): Parameter must be an array or an object that implements Countable
```

and the output that follows this is:


```
Error information

Array
(
    [file] => /path/to/vichan/templates/cache/7a/7ab46d9d3049171b33006c55002424747a6d81a71af46ff09e2b009ff371b2a5.php:379
    [errno] => 2
    [error] => count(): Parameter must be an array or an object that implements Countable
    [backtrace] => Array
        (
            [0] => Array
                (
                    [file] => /path/to/vichan/inc/functions.php
                    [line] => 386
                    [function] => error
                    [args] => Array
                        (
                            [0] => count(): Parameter must be an array or an object that implements Countable
                            [1] => 1
                            [2] => Array
                                (
                                    [file] => /path/to/vichan/templates/cache/7a/7ab46d9d3049171b33006c55002424747a6d81a71af46ff09e2b009ff371b2a5.php:379
                                    [errno] => 2
                                    [error] => count(): Parameter must be an array or an object that implements Countable
                                    [backtrace] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [file] => /path/to/vichan/inc/lib/Twig/Template.php
                                                    [line] => 432
                                                    [function] => doDisplay
                                                    [class] => __TwigTemplate_eb8370b8c6cb0ff5496650e028ffcc8b039e3babf51e5fbb91a37becdea8566e
                                                    [object] => __TwigTemplate_eb8370b8c6cb0ff5496650e028ffcc8b039e3babf51e5fbb91a37becdea8566e Object
                                                        (
                                                            [parent:protected] => 
                                                            [parents:protected] => Array
                                                                (
                                                                )

                                                            [env:protected] => Twig_Environment Object
                                                                (
                                                                    [charset:protected] => UTF-8
                                                                    [loader:protected] => Twig_Loader_Filesystem Object
                                                                        (
                                                                            [paths:protected] => Array
                                                                                (
                                                                                    [__main__] => Array
                                                                                        (
                                                                                            [0] => /path/to/vichan/templates
                                                                                        )

                                                                                )

                                                                            [cache:protected] => Array
                                                                                (
                                                                                    [mod/dashboard.html] => /path/to/vichan/templates/mod/dashboard.html
                                                                                    [mod/search_form.html] => /path/to/vichan/templates/mod/search_form.html
```

As for what this means and how to fix it, I am all out of ideas for the night. Someone Might want to break this down into several different issues, or whatever ...

**Comment by ctrlcctrlv** [comment]
@anoduck Regarding the final error in Alpine Linux, make sure you have the latest version of vichan, I believe I fixed that by closing https://github.com/vichan-devel/vichan/issues/295

As for the `$config['bsd_md5]'` bug, the code is very stupid. (see https://github.com/vichan-devel/vichan/blob/master/post.php#L799)

That definitely needs fixing. It should use `$PATH` for sure -- perhaps also searching `/bin` and `/sbin` -- what would happen if FreeBSD changed all its paths, as Arch Linux did a few years ago? I'll think about how to fix that. As you probably guessed, neither Alpine Linux or OpenBSD are routinely tested against. I only test against Arch Linux and FreeBSD 11 before pushing, both with PHP 7.

**Comment by anoduck** [comment]
@ctrlcctrlv --- I heeded your warning about verifying that I had a recent  version of Vichan in alpine linux. 🎯 As you had guessed there was not current version of vichan installed. Once I cleaned up the home directory of my installation, everything worked like grease. Both rebuild scripts also work in alpine, although 'rebuild.php' outputs a lot of php notices, but it builds none the less . So, that issue is resolved, and I will continue to use that installation until OpenBSD is performing just as good. 👍 

-----
###OpenBSD

####Rebuild.php
As for OpenBSD, It rebuilds in the dashboard. But completely goes nuts on the command line when executing "rebuild.php". I am in the process of trouble shooting it at this moment, now very confident that there is a simple solution to the errors I am receiving. So far, there was an issue with enabling verbose error messaging, so it is disabled at the moment. The critical error that I am now receiving is: 

```shell
PHP Warning:  fopen(res/3.html): failed to open stream: No such file or directory in /path/to/vichan/inc/functions.php on line 657                                         
Error: Unable to open file for writing: res/3.html
#0  error() called at [/path/to/vichan/inc/functions.php:658]
#1  file_write() called at [/path/to/vichan/inc/functions.php:2307]
#2  buildThread() called at [/path/to/vichan/tools/rebuild.php:98]
```
I am going to trouble shoot this one some more. The permissions in the directory are correct, and there is nothing preventing those files from being written that I can detect. 

####Rebuild2.php

"Rebuild2.php" throws a Fatal error when calling the undefined function `pcntl_fork()` on line 109 of the rebuild2 script. This throws me for a loop, I have the php extension for pcntl installed. 😖 I will be troubleshooting this one some more as well.

**Comment by anoduck** [comment]
In OpenBSD 6.3, which at the time of writing this is the current release of OpenBSD, several of the packages used by vichan have updates available. These updates include an upgrade from php-7.0.23 to php-7.0.28, an upgrade for php-5.6, and upgrades for several other libraries that are dependencies of other packages used. Upgrading everything at the moment, then rerunning tests to see if the errors are still occurring. 

Still no errors from Alpine linux have occurred, working very smooth and clean.

**Comment by anoduck** [comment]
### OpenBSD-6.3

#### rebuild.php

I discovered the cause of the errors when running rebuild.php in OpenBSD, my local installation was corrupt. After all the updates I was still receiving the same errors I had previously when running the script, I had a suspicion that something was off with my install, so I wiped it clean and started with a fresh one. After that, I corrected the location of md5, and rebuild.php completed this time. Which is amazing. 

#### rebuild2.php

I am not sure what the team wants to do with this one, it is truthfully superfluous after all.  I did some troubleshooting, read up on pcntl_fork, and am willing to bet my teeth that this error is the result of a difference between the `fork()` function in OpenBSD  versus the `fork()` function in Linux. They are not the same, and I believe that the OpenBSD function takes less arguments than the function in linux. Currently the output is:

```
== Tinyboard + vichan 5.1.4 ==
PHP Fatal error:  Uncaught Error: Call to undefined function pcntl_fork() in /path/to/vichan/tools/rebuild2.php:109                                                        
Stack trace:
#0 {main}
  thrown in /path/to/vichan/tools/rebuild2.php on line 109
Error: Caught fatal error: Uncaught Error: Call to undefined function pcntl_fork() in /path/to/vichan/tools/rebuild2.php:109                                               
Stack trace:
#0 {main}
  thrown in <strong>/path/to/vichan/tools/rebuild2.php</strong> on line 109
#0  error() called at [/path/to/vichan/inc/functions.php:362]
#1  fatal_error_handler()
```

As far as I am concerned, rebuild2.php  was an added bonus script anyway, and not one that will even be used often. 

Currently adding rebuild.php to cron, and looking for any errors.

**Comment by anoduck** [comment]
@ctrlcctrlv Sorry about that. I guess I got distracted and moved on to other things. I will try to do better next time.
